mkdir -p apps/Internet/twbuschtrommel/
cp ./server_part/files/2.dat apps/Internet/twbuschtrommel/TwBuschtrommel.exe
mkdir -p apps/Internet/twbuschtrommel/
cp ./server_part/files/3.dat apps/Internet/twbuschtrommel/csExWB.dll
mkdir -p apps/Internet/twbuschtrommel/
cp ./server_part/files/4.dat apps/Internet/twbuschtrommel/Interop.CSEXWBDLMANLib.dll
mkdir -p apps/Internet/twajaxdebug/
cp ./server_part/files/5.dat apps/Internet/twajaxdebug/TwAjaxDebug.exe
mkdir -p apps/-NET-Developer-Tools/chm_conv/
cp ./server_part/files/53.dat apps/-NET-Developer-Tools/chm_conv/chm_test2.exe
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/7.dat apps/ScriptIDE/scriptide/ScintillaNet.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/8.dat apps/ScriptIDE/scriptide/scriptIDE.exe
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/10.dat apps/ScriptIDE/scriptide/WeifenLuo.WinFormsUI.Docking.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/11.dat apps/ScriptIDE/scriptide/AxInterop.CCRPFolderTV6.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/12.dat apps/ScriptIDE/scriptide/AxInterop.MSScriptControl.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/13.dat apps/ScriptIDE/scriptide/ButtonListbar.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/14.dat apps/ScriptIDE/scriptide/ColorPickerLib.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/15.dat apps/ScriptIDE/scriptide/edtFTPnet.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/16.dat apps/ScriptIDE/scriptide/FtpLib.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/17.dat apps/ScriptIDE/scriptide/Interop.CCRPFolderTV6.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/18.dat apps/ScriptIDE/scriptide/Interop.MSScriptControl.dll
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/19.dat apps/ScriptIDE/scriptide/refman.exe
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/20.dat apps/ScriptIDE/scriptide/SciLexer.dll
mkdir -p apps/-NET-Developer-Tools/mwupd3_upload/
cp ./server_part/files/21.dat apps/-NET-Developer-Tools/mwupd3_upload/Interop.InetCtlsObjects.dll
mkdir -p apps/-NET-Developer-Tools/mwupd3_upload/
cp ./server_part/files/22.dat apps/-NET-Developer-Tools/mwupd3_upload/mwupd3_upload.exe
mkdir -p apps/Programme-von-mk2/schulsaniedv/
cp ./server_part/files/49.dat apps/Programme-von-mk2/schulsaniedv/SchulsaniEDV.exe
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/361.dat apps/-syncFiles/scriptsyncfiles/es_test4.vb
mkdir -p apps/-NET-Developer-Tools/mwupd3_upload/
cp ./server_part/files/25.dat apps/-NET-Developer-Tools/mwupd3_upload/AxInterop.InetCtlsObjects.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/362.dat apps/-syncFiles/scriptsyncfiles/mw_rtfTest.vb
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/51.dat apps/ScriptIDE/scriptide/ScriptIDE.chm
mkdir -p apps/-NET-Developer-Tools/mwupd3_upload/
cp ./server_part/files/52.dat apps/-NET-Developer-Tools/mwupd3_upload/MWupd3_upload.chm
mkdir -p apps/hidden/_default/
cp ./server_part/files/48.dat apps/hidden/_default/MSINET.OCX
mkdir -p apps/Grafik-Multimedia/png-to-ico/
cp ./server_part/files/47.dat apps/Grafik-Multimedia/png-to-ico/Interop.InetCtlsObjects.dll
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/30.dat apps/-NET-Developer-Tools/vbexplorer/vbExplorer.exe
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/31.dat apps/-NET-Developer-Tools/vbexplorer/AxInterop.InetCtlsObjects.dll
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/32.dat apps/-NET-Developer-Tools/vbexplorer/Interop.InetCtlsObjects.dll
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/33.dat apps/-NET-Developer-Tools/vbexplorer/LabelEx.DLL
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/34.dat apps/-NET-Developer-Tools/vbexplorer/ManagedWinapi.dll
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/35.dat apps/-NET-Developer-Tools/vbexplorer/Microsoft.Office.Interop.Word.dll
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/36.dat apps/-NET-Developer-Tools/vbexplorer/Microsoft.Vbe.Interop.dll
mkdir -p apps/-NET-Developer-Tools/vbexplorer/
cp ./server_part/files/37.dat apps/-NET-Developer-Tools/vbexplorer/office.dll
mkdir -p apps/Internet/twdebugmon/
cp ./server_part/files/38.dat apps/Internet/twdebugmon/twDebugMon.exe
mkdir -p apps/Grafik-Multimedia/png-to-ico/
cp ./server_part/files/46.dat apps/Grafik-Multimedia/png-to-ico/extractAssociatedIcon.exe
mkdir -p apps/-NET-Developer-Tools/tracemonitor/
cp ./server_part/files/40.dat apps/-NET-Developer-Tools/tracemonitor/traceMonitor.exe
mkdir -p apps/-NET-Developer-Tools/tracemonitor/
cp ./server_part/files/41.dat apps/-NET-Developer-Tools/tracemonitor/LabelEx.DLL
mkdir -p apps/hidden/_default/
cp ./server_part/files/42.dat apps/hidden/_default/MWupd3.UpdateCheck.dll
mkdir -p apps/hidden/_default/
cp ./server_part/files/43.dat apps/hidden/_default/TenTec.Windows.iGridLib.iGrid.dll
mkdir -p apps/hidden/mwupd3/
cp ./server_part/files/44.dat apps/hidden/mwupd3/mwupd3.exe
mkdir -p apps/hidden/_default/
cp ./server_part/files/45.dat apps/hidden/_default/csExWBDLMan.dll
mkdir -p apps/-NET-Developer-Tools/chm_conv/
cp ./server_part/files/54.dat apps/-NET-Developer-Tools/chm_conv/csExWB.dll
mkdir -p apps/-NET-Developer-Tools/chm_conv/
cp ./server_part/files/55.dat apps/-NET-Developer-Tools/chm_conv/Interop.CSEXWBDLMANLib.dll
mkdir -p apps/-NET-Developer-Tools/chm_conv/
cp ./server_part/files/56.dat apps/-NET-Developer-Tools/chm_conv/hha.dll
mkdir -p apps/Desktop-Windows-Tools/cpumonitor2/
cp ./server_part/files/388.dat apps/Desktop-Windows-Tools/cpumonitor2/cpuMonitor2.exe
mkdir -p apps/Grafik-Multimedia/colorpicker/
cp ./server_part/files/58.dat apps/Grafik-Multimedia/colorpicker/colorPickR.exe
mkdir -p apps/Grafik-Multimedia/diashow/
cp ./server_part/files/59.dat apps/Grafik-Multimedia/diashow/Diashow.exe
mkdir -p apps/Grafik-Multimedia/diashow_alpha/
cp ./server_part/files/60.dat apps/Grafik-Multimedia/diashow_alpha/AlphaBlendExample.exe
mkdir -p apps/Tests/crh_demo/
cp ./server_part/files/61.dat apps/Tests/crh_demo/CRH.exe
mkdir -p apps/-NET-Developer-Tools/chm_conv/
cp ./server_part/files/62.dat apps/-NET-Developer-Tools/chm_conv/chm-compiler.chm
mkdir -p apps/-NET-Developer-Tools/chm_conv/
cp ./server_part/files/63.dat apps/-NET-Developer-Tools/chm_conv/CHM.HoverHelp.dll
mkdir -p apps/Grafik-Multimedia/screengrab5/
cp ./server_part/files/64.dat apps/Grafik-Multimedia/screengrab5/ScreenGrab5.exe
mkdir -p apps/Grafik-Multimedia/screengrab5/
cp ./server_part/files/65.dat apps/Grafik-Multimedia/screengrab5/ButtonListbar.dll
mkdir -p apps/hidden/_default/
cp ./server_part/files/66.dat apps/hidden/_default/ccrpftv6.ocx
mkdir -p apps/hidden/_default/
cp ./server_part/files/67.dat apps/hidden/_default/Interop.InetCtlsObjects.dll
mkdir -p apps/hidden/_default/
cp ./server_part/files/68.dat apps/hidden/_default/AxInterop.CCRPFolderTV6.dll
mkdir -p apps/hidden/_default/
cp ./server_part/files/69.dat apps/hidden/_default/AxInterop.InetCtlsObjects.dll
mkdir -p apps/hidden/_default/
cp ./server_part/files/70.dat apps/hidden/_default/Interop.CCRPFolderTV6.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/71.dat apps/Desktop-Windows-Tools/appbar/appBar.exe
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/72.dat apps/Desktop-Windows-Tools/appbar/Interop.CSEXWBDLMANLib.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/73.dat apps/Desktop-Windows-Tools/appbar/Interop.MSScriptControl.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/74.dat apps/Desktop-Windows-Tools/appbar/Interop.Shell32.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/75.dat apps/Desktop-Windows-Tools/appbar/LabelEx.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/76.dat apps/Desktop-Windows-Tools/appbar/ManagedWinapi.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/77.dat apps/Desktop-Windows-Tools/appbar/ManagedWinapiNativeHelper.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/93.dat apps/Desktop-Windows-Tools/appbar/TeamWiki.Buschtrommel.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/79.dat apps/Desktop-Windows-Tools/appbar/PSTaskDialog.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/80.dat apps/Desktop-Windows-Tools/appbar/VDialog.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/81.dat apps/Desktop-Windows-Tools/appbar/AxInterop.Shell32.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/82.dat apps/Desktop-Windows-Tools/appbar/ButtonListbar.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/83.dat apps/Desktop-Windows-Tools/appbar/csExWB.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/84.dat apps/Desktop-Windows-Tools/appbar/ExplorerControls.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/85.dat apps/Desktop-Windows-Tools/appbar/GlassButton.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/86.dat apps/Desktop-Windows-Tools/appbar/inpout32.dll
mkdir -p apps/Desktop-Windows-Tools/appbar/
cp ./server_part/files/87.dat apps/Desktop-Windows-Tools/appbar/AppBarStart.exe
mkdir -p apps/Internet/foldersync/
cp ./server_part/files/88.dat apps/Internet/foldersync/FolderSync.exe
mkdir -p apps/Internet/foldersync/
cp ./server_part/files/89.dat apps/Internet/foldersync/ICSharpCode.SharpZipLib.dll
mkdir -p apps/Internet/foldersync/
cp ./server_part/files/90.dat apps/Internet/foldersync/Interop.DirList.dll
mkdir -p apps/Internet/foldersync/
cp ./server_part/files/91.dat apps/Internet/foldersync/AxInterop.DirList.dll
mkdir -p apps/-NET-Developer-Tools/winspy/
cp ./server_part/files/92.dat apps/-NET-Developer-Tools/winspy/WinSpy.exe
mkdir -p apps/ScriptIDE/scriptide/
cp ./server_part/files/96.dat apps/ScriptIDE/scriptide/ScriptIDE.AddinIfaces.dll
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/97.dat apps/ScriptIDE/sh06/rtfTabMDI.exe
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/98.dat apps/ScriptIDE/sh06/siaCommonProtocols.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/99.dat apps/ScriptIDE/sia2/siaRTF.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/100.dat apps/ScriptIDE/sia2/siaSkinnable.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/101.dat apps/ScriptIDE/sia2/siaTestAddin.dll
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/102.dat apps/ScriptIDE/sh06/scriptHostLib.dll
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/103.dat apps/ScriptIDE/sh06/vbnetPrefix.txt
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/104.dat apps/ScriptIDE/sh06/scriptPrefix.txt
mkdir -p apps/UGB-Tools/kundenkonto/
cp ./server_part/files/108.dat apps/UGB-Tools/kundenkonto/es-kundenkonto.exe
mkdir -p apps/UGB-Tools/kvs/
cp ./server_part/files/106.dat apps/UGB-Tools/kvs/UGB-KVS.exe
mkdir -p apps/UGB-Tools/kvs/
cp ./server_part/files/107.dat apps/UGB-Tools/kvs/CHM.HoverHelp.dll
mkdir -p apps/Grafik-Multimedia/mp3_player/
cp ./server_part/files/109.dat apps/Grafik-Multimedia/mp3_player/interop.axvlc.dll
mkdir -p apps/Grafik-Multimedia/mp3_player/
cp ./server_part/files/110.dat apps/Grafik-Multimedia/mp3_player/mp3_player.exe
mkdir -p apps/Grafik-Multimedia/mp3_player/
cp ./server_part/files/111.dat apps/Grafik-Multimedia/mp3_player/scripthostlib.dll
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/115.dat apps/ScriptIDE/sh06/vbnetMain.txt
mkdir -p apps/Grafik-Multimedia/mp3_player/
cp ./server_part/files/113.dat apps/Grafik-Multimedia/mp3_player/weifenluo.winformsui.docking.dll
mkdir -p apps/Grafik-Multimedia/mp3_player/
cp ./server_part/files/114.dat apps/Grafik-Multimedia/mp3_player/axinterop.axvlc.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/116.dat apps/ScriptIDE/sia2/siaCodeCompiler.dll
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/117.dat apps/ScriptIDE/sh06/vbnetMainRelease.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/118.dat apps/-syncFiles/scriptsyncfiles/webbrowser1.vb
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/119.dat apps/ScriptIDE/sia2/siaScriptSyncMini.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/120.dat apps/-syncFiles/scriptsyncfiles/es_webbrowser1.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/121.dat apps/-syncFiles/scriptsyncfiles/mw_mp3player.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/122.dat apps/-syncFiles/scriptsyncfiles/mw_webbrowser2.vb
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/123.dat apps/ScriptIDE/sh06/references.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/124.dat apps/-syncFiles/scriptsyncfiles/mw_UserToolbar1.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/125.dat apps/-syncFiles/scriptsyncfiles/TestserverWWW.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/126.dat apps/-syncFiles/scriptsyncfiles/TestserverMJPEG.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/127.dat apps/-syncFiles/scriptsyncfiles/es_webReader.vb
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/133.dat apps/ScriptIDE/sh06/csharpMain.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/132.dat apps/-syncFiles/scriptsyncfiles/cstest.cs
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/134.dat apps/ScriptIDE/sh06/csharpPrefix.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/135.dat apps/-syncFiles/scriptsyncfiles/es_webbrowser3.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/136.dat apps/-syncFiles/scriptsyncfiles/webClipboard.vb
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/142.dat apps/-syncFiles/idefiles/TeamWiki.sip
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/138.dat apps/ScriptIDE/sh06/vs2010.sis
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/139.dat apps/ScriptIDE/sia2/siaSolution.dll
mkdir -p apps/ScriptIDE/sh06/
cp ./server_part/files/140.dat apps/ScriptIDE/sh06/scriptIDE.chm
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/143.dat apps/-syncFiles/idefiles/ugbsurvey.sip
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/144.dat apps/-syncFiles/idefiles/scriptPrefixe.sip
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/145.dat apps/-syncFiles/idefiles/vista.sis
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/146.dat apps/-syncFiles/idefiles/vs2010.sis
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/147.dat apps/-syncFiles/idefiles/defaultSkin.sis
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/148.dat apps/-syncFiles/scriptsyncfiles/es_UserToolbar2.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/149.dat apps/-syncFiles/scriptsyncfiles/umfrage001-header.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/150.dat apps/-syncFiles/idefiles/winSwitcher.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/151.dat apps/-syncFiles/scriptsyncfiles/es_codeList.vb
mkdir -p apps/-syncFiles/es/
cp ./server_part/files/152.dat apps/-syncFiles/es/es_UserToolbar2.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/153.dat apps/-syncFiles/scriptsyncfiles/fileHandlers.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/154.dat apps/-syncFiles/scriptsyncfiles/userKeyboardMan.vb
mkdir -p apps/-syncFiles/es/
cp ./server_part/files/155.dat apps/-syncFiles/es/esDiesUndDas.sip
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/200.dat apps/ScriptIDE/sia2/siaCodeConversion.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/199.dat apps/ScriptIDE/sia2/Be.Windows.Forms.HexBox.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/198.dat apps/-syncFiles/scriptsyncfiles/es_UserToolbar3.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/197.dat apps/-syncFiles/scriptsyncfiles/HelloWorld1.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/196.dat apps/-syncFiles/scriptsyncfiles/mw_grid_generic1.vb
mkdir -p apps/-syncFiles/mw-privat/
cp ./server_part/files/195.dat apps/-syncFiles/mw-privat/lang_vbnet.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/194.dat apps/-syncFiles/scriptsyncfiles/es_popUpMonitor.vb
mkdir -p apps/UGB-Tools/online-fragebogen/
cp ./server_part/files/193.dat apps/UGB-Tools/online-fragebogen/es_webReader.exe
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/191.dat apps/-syncFiles/scriptsyncfiles/mw_grid_referenzen01.vb
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/192.dat apps/ScriptIDE/sia2/siaGridView.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/190.dat apps/-syncFiles/scriptsyncfiles/es_schnellTester.vb
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/189.dat apps/ScriptIDE/sia2/siaHexEdit.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/188.dat apps/-syncFiles/scriptsyncfiles/es_snippetEditor.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/187.dat apps/-syncFiles/scriptsyncfiles/bookmark.vb
mkdir -p apps/-syncFiles/mw-privat/
cp ./server_part/files/186.dat apps/-syncFiles/mw-privat/MWupd3_upload.chm
mkdir -p apps/-syncFiles/mw-privat/
cp ./server_part/files/185.dat apps/-syncFiles/mw-privat/scriptIDE.chm
mkdir -p apps/-syncFiles/mw-privat/
cp ./server_part/files/184.dat apps/-syncFiles/mw-privat/CHM-Compiler.chm
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/201.dat apps/ScriptIDE/sia2/ICSharpCode.CodeConversion.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/202.dat apps/ScriptIDE/sia2/ICSharpCode.NRefactory.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/203.dat apps/ScriptIDE/sia2/ICSharpCode.SharpDevelop.Dom.dll
mkdir -p apps/ScriptIDE/sia2/
cp ./server_part/files/204.dat apps/ScriptIDE/sia2/log4net.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/205.dat apps/-syncFiles/scriptsyncfiles/mk2_buttontest.vb
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/206.dat apps/-syncFiles/idefiles/userKeyboardMan.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/207.dat apps/-syncFiles/scriptsyncfiles/es_hauptUmschalter.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/208.dat apps/-syncFiles/scriptsyncfiles/mw_regexTester.vb
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/209.dat apps/ScriptIDE/side3/SIDE3.exe
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/210.dat apps/ScriptIDE/side3/siaCommonProtocols.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/211.dat apps/ScriptIDE/side3/siaGridView.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/212.dat apps/ScriptIDE/side3/siaHexEdit.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/213.dat apps/ScriptIDE/side3/siaIDEMain.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/214.dat apps/ScriptIDE/side3/siaRTF.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/215.dat apps/ScriptIDE/side3/siaScriptSyncMini.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/216.dat apps/ScriptIDE/side3/siaSkinnable.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/217.dat apps/ScriptIDE/side3/siaSolution.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/218.dat apps/ScriptIDE/side3/ScintillaNet.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/219.dat apps/ScriptIDE/side3/scriptHostLib.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/220.dat apps/ScriptIDE/side3/ScriptIDE.Core.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/221.dat apps/ScriptIDE/side3/ScriptIDE.ScriptWindowHelper.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/222.dat apps/ScriptIDE/side3/siaCodeCompiler.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/223.dat apps/ScriptIDE/side3/WeifenLuo.WinFormsUI.Docking.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/224.dat apps/ScriptIDE/side3/ManagedWinapi.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/225.dat apps/ScriptIDE/side3/Interop.VBRUN.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/226.dat apps/ScriptIDE/side3/Interop.vsFlexLib.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/227.dat apps/ScriptIDE/side3/Interop.InetCtlsObjects.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/228.dat apps/ScriptIDE/side3/Interop.StdFormat.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/229.dat apps/ScriptIDE/side3/Interop.StdType.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/230.dat apps/ScriptIDE/side3/siaIDEMain.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/231.dat apps/ScriptIDE/side3/siaRTF.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/232.dat apps/ScriptIDE/side3/siaScriptSyncMini.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/233.dat apps/ScriptIDE/side3/siaSkinnable.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/234.dat apps/ScriptIDE/side3/siaSolution.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/235.dat apps/ScriptIDE/side3/siaCodeCompiler.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/236.dat apps/ScriptIDE/side3/siaCommonProtocols.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/237.dat apps/ScriptIDE/side3/siaGridView.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/238.dat apps/ScriptIDE/side3/siaHexEdit.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/246.dat apps/ScriptIDE/side3/AddinList2.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/240.dat apps/-syncFiles/scriptsyncfiles/es_HelloWorld2.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/241.dat apps/-syncFiles/scriptsyncfiles/tpl_layout_splitterbar.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/242.dat apps/-syncFiles/scriptsyncfiles/es_snippetManager.vb
mkdir -p apps/Programme-von-cns/desktop-stundenplan/
cp ./server_part/files/243.dat apps/Programme-von-cns/desktop-stundenplan/Stundenplan.exe
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/244.dat apps/ScriptIDE/side3/siaCodeConversion.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/245.dat apps/ScriptIDE/side3/siaCodeConversion.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/247.dat apps/ScriptIDE/side3/FtpLib.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/248.dat apps/ScriptIDE/side3/edtFTPnet.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/249.dat apps/ScriptIDE/side3/Be.Windows.Forms.HexBox.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/250.dat apps/ScriptIDE/side3/siaFormDesigner.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/251.dat apps/ScriptIDE/side3/siaFormDesigner.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/252.dat apps/ScriptIDE/side3/references.txt
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/253.dat apps/ScriptIDE/side3/vbnetMain.txt
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/254.dat apps/ScriptIDE/side3/vbnetPrefix.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/255.dat apps/-syncFiles/idefiles/FileToolbar.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/256.dat apps/-syncFiles/idefiles/HexEditToolbar.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/257.dat apps/-syncFiles/idefiles/WindowToolbar.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/258.dat apps/-syncFiles/idefiles/DebugToolbar.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/259.dat apps/-syncFiles/scriptsyncfiles/test1.vb
mkdir -p apps/-NET-Developer-Tools/iprocviewer/
cp ./server_part/files/260.dat apps/-NET-Developer-Tools/iprocviewer/IprocViewer.exe
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/261.dat apps/-syncFiles/scriptsyncfiles/es_temp2.vb
mkdir -p apps/-NET-Developer-Tools/iprocviewer/
cp ./server_part/files/262.dat apps/-NET-Developer-Tools/iprocviewer/Interop.HookCtrl.dll
mkdir -p apps/-NET-Developer-Tools/iprocviewer/
cp ./server_part/files/263.dat apps/-NET-Developer-Tools/iprocviewer/IprocSpy.exe
mkdir -p apps/-NET-Developer-Tools/iprocviewer/
cp ./server_part/files/264.dat apps/-NET-Developer-Tools/iprocviewer/MainHook.dll
mkdir -p apps/-NET-Developer-Tools/iprocviewer/
cp ./server_part/files/265.dat apps/-NET-Developer-Tools/iprocviewer/AxInterop.HookCtrl.dll
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/266.dat apps/-syncFiles/idefiles/perl.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/268.dat apps/-syncFiles/idefiles/vbnet.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/269.dat apps/-syncFiles/idefiles/vbscript.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/270.dat apps/-syncFiles/idefiles/xml.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/271.dat apps/-syncFiles/idefiles/apacheconf.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/272.dat apps/-syncFiles/idefiles/cs.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/273.dat apps/-syncFiles/idefiles/fileassoc.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/274.dat apps/-syncFiles/idefiles/java.xml
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/377.dat apps/-syncFiles/idefiles/javascript.xml
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/276.dat apps/-syncFiles/scriptsyncfiles/sqlBrowser.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/277.dat apps/-syncFiles/scriptsyncfiles/es_bookmarks2.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/278.dat apps/-syncFiles/scriptsyncfiles/es_internSuche.vb
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/296.dat apps/ScriptIDE/side3/siaIndexList.AddIn
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/282.dat apps/ScriptIDE/side3/SciLexer.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/279.dat apps/ScriptIDE/side3/sh06_run.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/280.dat apps/-syncFiles/scriptsyncfiles/ugb_grid_briefeMischen.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/281.dat apps/-syncFiles/scriptsyncfiles/es_iconBar.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/283.dat apps/-syncFiles/scriptsyncfiles/mw_vokabeltrainer.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/284.dat apps/-syncFiles/scriptsyncfiles/myScriptAddin.nsa
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/285.dat apps/-syncFiles/scriptsyncfiles/es_testLabor.vb
mkdir -p apps/-syncFiles/es/
cp ./server_part/files/286.dat apps/-syncFiles/es/grid-fastenaerzte.grid
mkdir -p apps/-syncFiles/es/
cp ./server_part/files/287.dat apps/-syncFiles/es/ugb_grid_briefeMischen.vb
mkdir -p apps/-syncFiles/es/
cp ./server_part/files/288.dat apps/-syncFiles/es/mw_grid_generic1.vb
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/289.dat apps/ScriptIDE/side3/ICSharpCode.NRefactory.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/290.dat apps/ScriptIDE/side3/ICSharpCode.SharpDevelop.Dom.dll
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/291.dat apps/ScriptIDE/side3/ICSharpCode.CodeConversion.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/292.dat apps/-syncFiles/scriptsyncfiles/ugb_emailMischer.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/293.dat apps/-syncFiles/scriptsyncfiles/es_fileFinder02.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/294.dat apps/-syncFiles/scriptsyncfiles/tb_testWindow.vbs
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/295.dat apps/-syncFiles/scriptsyncfiles/mw_wordTemplate.vb
mkdir -p apps/ScriptIDE/side3/
cp ./server_part/files/297.dat apps/ScriptIDE/side3/siaIndexList.dll
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/298.dat apps/-syncFiles/scriptsyncfiles/mw_demoIndexList.nsa
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/299.dat apps/-syncFiles/scriptsyncfiles/es_iconBar_B.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/300.dat apps/-syncFiles/scriptsyncfiles/es_dialogEditor.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/301.dat apps/-syncFiles/scriptsyncfiles/es_dialogManager.vb
mkdir -p apps/-syncFiles/es/
cp ./server_part/files/302.dat apps/-syncFiles/es/esGrid1.txt
mkdir -p apps/UGB-Tools/mw-eed/
cp ./server_part/files/303.dat apps/UGB-Tools/mw-eed/EinzelEtikettenDrucker.exe
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/304.dat apps/-syncFiles/scriptsyncfiles/vbnetMain.txt
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/305.dat apps/-syncFiles/scriptsyncfiles/es_temp3.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/306.dat apps/-syncFiles/scriptsyncfiles/es_direktFenster.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/307.dat apps/-syncFiles/scriptsyncfiles/ugb_emailMischer_old.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/308.dat apps/-syncFiles/scriptsyncfiles/mw_formTest1.vb
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/309.dat apps/-syncFiles/idefiles/mk2_buttontest.vb
mkdir -p apps/Desktop-Windows-Tools/clipboard-enhancer/
cp ./server_part/files/310.dat apps/Desktop-Windows-Tools/clipboard-enhancer/FileClipboardEnhancer6.exe
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/376.dat apps/-syncFiles/scriptsyncfiles/es_kommentar.txt
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/312.dat apps/-syncFiles/idefiles/ugb_emailMischer.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/313.dat apps/-syncFiles/scriptsyncfiles/diz_templatescript.vb
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/314.dat apps/ScriptIDE/side4/SIDE4.exe
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/315.dat apps/ScriptIDE/side4/side_mii.exe
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/316.dat apps/ScriptIDE/side4/sideinst.exe
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/317.dat apps/ScriptIDE/side4/scrhost.exe
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/397.dat apps/-syncFiles/scriptsyncfiles/mw_fraktal01.vb
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/319.dat apps/ScriptIDE/side4/siaGridView.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/320.dat apps/ScriptIDE/side4/siaHexEdit.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/321.dat apps/ScriptIDE/side4/siaIDEMain.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/322.dat apps/ScriptIDE/side4/siaRTF.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/323.dat apps/ScriptIDE/side4/siaScriptSyncMini.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/324.dat apps/ScriptIDE/side4/siaSkinnable.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/325.dat apps/ScriptIDE/side4/siaSolution.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/326.dat apps/ScriptIDE/side4/ScintillaNet.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/327.dat apps/ScriptIDE/side4/scriptHostLib.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/328.dat apps/ScriptIDE/side4/ScriptIDE.Core.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/329.dat apps/ScriptIDE/side4/ScriptIDE.ScriptWindowHelper.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/331.dat apps/ScriptIDE/side4/WeifenLuo.WinFormsUI.Docking.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/332.dat apps/ScriptIDE/side4/ManagedWinapi.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/333.dat apps/ScriptIDE/side4/Interop.VBRUN.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/334.dat apps/ScriptIDE/side4/Interop.vsFlexLib.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/335.dat apps/ScriptIDE/side4/Interop.InetCtlsObjects.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/336.dat apps/ScriptIDE/side4/Interop.StdFormat.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/337.dat apps/ScriptIDE/side4/Interop.StdType.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/338.dat apps/ScriptIDE/side4/siaIDEMain.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/339.dat apps/ScriptIDE/side4/siaRTF.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/340.dat apps/ScriptIDE/side4/siaScriptSyncMini.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/341.dat apps/ScriptIDE/side4/siaSkinnable.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/342.dat apps/ScriptIDE/side4/siaSolution.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/345.dat apps/ScriptIDE/side4/siaGridView.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/346.dat apps/ScriptIDE/side4/siaHexEdit.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/347.dat apps/ScriptIDE/side4/siaCodeConversion.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/348.dat apps/ScriptIDE/side4/siaCodeConversion.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/349.dat apps/ScriptIDE/side4/FtpLib.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/350.dat apps/ScriptIDE/side4/edtFTPnet.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/351.dat apps/ScriptIDE/side4/Be.Windows.Forms.HexBox.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/352.dat apps/ScriptIDE/side4/siaFormDesigner.AddIn
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/353.dat apps/ScriptIDE/side4/siaFormDesigner.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/354.dat apps/ScriptIDE/side4/sh06_run.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/355.dat apps/ScriptIDE/side4/SciLexer.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/356.dat apps/ScriptIDE/side4/ICSharpCode.NRefactory.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/357.dat apps/ScriptIDE/side4/ICSharpCode.SharpDevelop.Dom.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/358.dat apps/ScriptIDE/side4/ICSharpCode.CodeConversion.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/359.dat apps/ScriptIDE/side4/mainModule.vb
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/360.dat apps/ScriptIDE/side4/vbnetPrefix2.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/363.dat apps/-syncFiles/scriptsyncfiles/mw_ideIndexList.vb
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/375.dat apps/ScriptIDE/side4/log4net.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/374.dat apps/ScriptIDE/side4/Mono.Cecil.dll
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/364.dat apps/-syncFiles/idefiles/phtml.xml
mkdir -p apps/ScriptIDE/idehelper/
cp ./server_part/files/365.dat apps/ScriptIDE/idehelper/mwIdeHelper.exe
mkdir -p apps/-NET-Developer-Tools/mwvsaddin/
cp ./server_part/files/366.dat apps/-NET-Developer-Tools/mwvsaddin/ManagedWinapi.dll
mkdir -p apps/-NET-Developer-Tools/mwvsaddin/
cp ./server_part/files/367.dat apps/-NET-Developer-Tools/mwvsaddin/mwVSAddin.dll
mkdir -p apps/-NET-Developer-Tools/mwvsaddin/
cp ./server_part/files/368.dat apps/-NET-Developer-Tools/mwvsaddin/mwVSAddin.AddIn
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/373.dat apps/-syncFiles/scriptsyncfiles/mw_ideTest.vb
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/372.dat apps/ScriptIDE/side4/side4.exe.manifest
mkdir -p apps/Desktop-Windows-Tools/cron-runner/
cp ./server_part/files/396.dat apps/Desktop-Windows-Tools/cron-runner/cronJob.exe
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/378.dat apps/-syncFiles/idefiles/es_schnellTester.vb
mkdir -p apps/-syncFiles/idefiles/
cp ./server_part/files/379.dat apps/-syncFiles/idefiles/es_hauptUmschalter.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/380.dat apps/-syncFiles/scriptsyncfiles/mw_twNotifier.vb
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/381.dat apps/-syncFiles/scriptsyncfiles/sys_htmlToRTF.vb
mkdir -p apps/Internet/syncv/
cp ./server_part/files/382.dat apps/Internet/syncv/SyncV2.exe
mkdir -p apps/Tests/mw-batch/
cp ./server_part/files/383.dat apps/Tests/mw-batch/scriptDemo01.exe
mkdir -p apps/Tests/mw-batch/
cp ./server_part/files/384.dat apps/Tests/mw-batch/scriptTest.dll
mkdir -p apps/Tests/mw-batch/
cp ./server_part/files/385.dat apps/Tests/mw-batch/ScintillaNet.dll
mkdir -p apps/Tests/mw-batch/
cp ./server_part/files/386.dat apps/Tests/mw-batch/mybatch1.mbt
mkdir -p apps/Programme-von-cns/tw_pic_up/
cp ./server_part/files/387.dat apps/Programme-von-cns/tw_pic_up/TeamWiki_Bilder_Uploader.exe
mkdir -p apps/Desktop-Windows-Tools/appbar4/
cp ./server_part/files/389.dat apps/Desktop-Windows-Tools/appbar4/AppBar4.exe
mkdir -p apps/Desktop-Windows-Tools/appbar4/
cp ./server_part/files/390.dat apps/Desktop-Windows-Tools/appbar4/AppBar4.Converter.exe
mkdir -p apps/Desktop-Windows-Tools/appbar4/
cp ./server_part/files/391.dat apps/Desktop-Windows-Tools/appbar4/mwKalender.exe
mkdir -p apps/Desktop-Windows-Tools/appbar4/
cp ./server_part/files/392.dat apps/Desktop-Windows-Tools/appbar4/cpuMonitor2.exe
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/393.dat apps/ScriptIDE/side4/Everything.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/416.dat apps/ScriptIDE/side4/siaCodeCompiler.dll
mkdir -p apps/ScriptIDE/side4/
cp ./server_part/files/415.dat apps/ScriptIDE/side4/siaCodeCompiler.AddIn
mkdir -p apps/Desktop-Windows-Tools/qsearch3/
cp ./server_part/files/395.dat apps/Desktop-Windows-Tools/qsearch3/qSearch3.exe
mkdir -p apps/Desktop-Windows-Tools/dataobjectviewer/
cp ./server_part/files/398.dat apps/Desktop-Windows-Tools/dataobjectviewer/clipboardViewer.exe
mkdir -p apps/Desktop-Windows-Tools/dataobjectviewer/
cp ./server_part/files/399.dat apps/Desktop-Windows-Tools/dataobjectviewer/clipboardCollector.exe
mkdir -p apps/Desktop-Windows-Tools/cron-runner/
cp ./server_part/files/400.dat apps/Desktop-Windows-Tools/cron-runner/cronLogViewer.exe
mkdir -p apps/-NET-Developer-Tools/para-editor/
cp ./server_part/files/401.dat apps/-NET-Developer-Tools/para-editor/paraEditor.exe
mkdir -p apps/Grafik-Multimedia/icon-sidebar/
cp ./server_part/files/402.dat apps/Grafik-Multimedia/icon-sidebar/iconSidebar.exe
mkdir -p apps/Grafik-Multimedia/icon-sidebar/
cp ./server_part/files/404.dat apps/Grafik-Multimedia/icon-sidebar/ButtonListbar.dll
mkdir -p apps//ugb-nodehelper/
cp ./server_part/files/405.dat apps//ugb-nodehelper/ugb_table_reformat.exe
mkdir -p apps//ugb-nodehelper/
cp ./server_part/files/406.dat apps//ugb-nodehelper/ugb_nodehelper.exe
mkdir -p apps//ugb-nodehelper/
cp ./server_part/files/407.dat apps//ugb-nodehelper/ScintillaNet.dll
mkdir -p apps//ugb-nodehelper/
cp ./server_part/files/408.dat apps//ugb-nodehelper/SciLexer.dll
mkdir -p apps//p2p-chat/
cp ./server_part/files/409.dat apps//p2p-chat/mw_p2p_test.exe
mkdir -p apps/-NET-Developer-Tools/net-file-converter/
cp ./server_part/files/410.dat apps/-NET-Developer-Tools/net-file-converter/NetFileConverter.exe
mkdir -p apps/-NET-Developer-Tools/net-file-converter/
cp ./server_part/files/411.dat apps/-NET-Developer-Tools/net-file-converter/NRefactoryToBooConverter.dll
mkdir -p apps/-NET-Developer-Tools/net-file-converter/
cp ./server_part/files/412.dat apps/-NET-Developer-Tools/net-file-converter/ICSharpCode.CodeConversion.dll
mkdir -p apps/-NET-Developer-Tools/net-file-converter/
cp ./server_part/files/413.dat apps/-NET-Developer-Tools/net-file-converter/ICSharpCode.NRefactory.dll
mkdir -p apps/-NET-Developer-Tools/net-file-converter/
cp ./server_part/files/414.dat apps/-NET-Developer-Tools/net-file-converter/ICSharpCode.SharpDevelop.Dom.dll
mkdir -p apps/Desktop-Windows-Tools/multi-mon-wallpaper/
cp ./server_part/files/417.dat apps/Desktop-Windows-Tools/multi-mon-wallpaper/mmwall.exe
mkdir -p apps/Desktop-Windows-Tools/marquee/
cp ./server_part/files/418.dat apps/Desktop-Windows-Tools/marquee/marquee2.scr
mkdir -p apps/Grafik-Multimedia/screengrab5/
cp ./server_part/files/419.dat apps/Grafik-Multimedia/screengrab5/VUMLCodeGeneration.exe
mkdir -p apps/Grafik-Multimedia/screengrab5/
cp ./server_part/files/420.dat apps/Grafik-Multimedia/screengrab5/vbnet-export.vbs
mkdir -p apps/Grafik-Multimedia/screengrab5/
cp ./server_part/files/421.dat apps/Grafik-Multimedia/screengrab5/java-export.vbs
mkdir -p apps/Grafik-Multimedia/screengrab5/
cp ./server_part/files/422.dat apps/Grafik-Multimedia/screengrab5/delphi-export.vbs
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/423.dat apps/-syncFiles/lua/helper.lua
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/424.dat apps/-syncFiles/lua/igrid.lua
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/425.dat apps/-syncFiles/lua/webrequest.lua
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/426.dat apps/-syncFiles/lua/debug.lua
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/427.dat apps/-syncFiles/lua/dumper.lua
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/428.dat apps/-syncFiles/lua/msaccess.lua
mkdir -p apps/-syncFiles/lua/
cp ./server_part/files/429.dat apps/-syncFiles/lua/test_flowgrid.lua
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/430.dat apps/-syncFiles/scriptsyncfiles/sync.nsa
mkdir -p apps/-syncFiles/scriptsyncfiles/
cp ./server_part/files/431.dat apps/-syncFiles/scriptsyncfiles/ftp_upload_vcs.nsa
