NewPart: projectname
esDiesUndDas.sip
NewPart: projecttree
00	File_loc:/c:/ypara/scriptide/bookmarks.txt	bookmarks.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/bookmarks.txt	
00	File_loc:/c:/ypara/scriptide/scriptclass/sqlbrowser.vb	sqlBrowser.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/sqlBrowser.vb	
00	File_loc:/c:/ypara/scriptide/scriptclass/es_webreader.vb	es_webReader.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/es_webReader.vb	
00	File_loc:/c:/ypara/scriptide/scriptclass/es_codelist.vb	es_codeList.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/es_codeList.vb	
00	File_loc:/c:/ypara/scriptide/scriptclass/userkeyboardman.vb	userKeyboardMan.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/userKeyboardMan.vb	
00	File_loc:/c:/ypara/scriptide/scriptclass/es_usertoolbar2.vb	es_UserToolbar2.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/es_UserToolbar2.vb	
00	File_loc:/c:/ypara/scriptide/scriptclass/es_webbrowser3.vb	es_webbrowser3.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/es_webbrowser3.vb	

NewPart: expanded
True
