NewPart: projectname
scriptPrefixe




NewPart: projecttree
00		C#	Folder	C		Folder		
01	File_loc:/c:/ypara/scriptide/scriptclass/csharpmain.txt	csharpMain.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/csharpMain.txt	
01	File_loc:/c:/ypara/scriptide/scriptclass/csharpprefix.txt	csharpPrefix.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/csharpPrefix.txt	
01	File_loc:/c:/ypara/scriptide/scriptclass/mw_webbrowser2.vb	mw_webbrowser2.vb	.VB	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/mw_webbrowser2.vb	
00		vb.NET	Folder	E		Folder		
01	File_loc:/c:/ypara/scriptide/scriptclass/vbnetmain.txt	vbnetMain.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/vbnetMain.txt	
01	File_loc:/c:/ypara/scriptide/scriptclass/vbnetmainrelease.txt	vbnetMainRelease.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/vbnetMainRelease.txt	
01	File_loc:/c:/ypara/scriptide/scriptclass/vbnetprefix.txt	vbnetPrefix.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/vbnetPrefix.txt	
00	File_loc:/c:/ypara/scriptide/scriptclass/scriptprefix.txt	scriptPrefix.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/scriptPrefix.txt	
00	File_loc:/c:/ypara/scriptide/scriptclass/references.txt	references.txt	.TXT	C		DefaultFile	loc:/C:/yPara/scriptIDE/scriptClass/references.txt	
00	File_c:\ypara\scriptide\scriptclass\cstest.cs	cstest.cs	.CS	C		DefaultFile	C:\yPara\scriptIDE\scriptClass\cstest.cs	

